name: "nsga3"

params:
  pop_size: 200
  n_gen: 100
  n_inner_waypoints: 5
  n_output_waypoints: 100
  decision_mode: "safety"
  min_dist: 1.5
  ignore_ratio: 0.1
  safety_margin: 1.0
  max_jerk: 200.0
  uniformity_std: 5.0
  max_battery_ratio: 5.0
