defaults:
  - _self_
  - environment: forest
  - optimizer: msffoa

simulation:
  duration_sec: 180
  gui: true
  pyb_freq: 240
  ctrl_freq: 48
  drone_model: "CF2X"
  physics: "PYB"
  sim_speed_multiplier: 5.0

seed: 42
experiment_name: "test_run"
debug: true
logging:
  enabled: true
  log_freq: 1.0

visualization:
  camera_follow: true
  tracked_drone_id: 0
  camera_distance: 1.0
  camera_yaw: -15.0
  camera_pitch: -30.0
  show_lidar_rays: false
  lidar_draw_interval: 5

hydra:
  run:
    dir: results/${now:%Y-%m-%d}/${now:%H-%M-%S}_${environment.name}_${hydra:runtime.choices.optimizer}
  
  job_logging:
    version: 1
    root:
      level: INFO
